language: minimal

# Install libraries required by the scripts
install: pip install --user -r requirements.txt

# Generate resourcepacks as ZIP-archives
script: ./scripts/generate_resourcepacks.sh

deploy:
  cleanup: false